/*
 * gpio_irq_device.h
 *
 *  Created on: 26 gen 2018
 *      Author: Gianluca
 */

#ifndef MBED_OS_TARGETS_TARGET_STMBLUE_TARGET_BLUENRG1_GPIO_IRQ_DEVICE_H_
#define MBED_OS_TARGETS_TARGET_STMBLUE_TARGET_BLUENRG1_GPIO_IRQ_DEVICE_H_




#endif /* MBED_OS_TARGETS_TARGET_STMBLUE_TARGET_BLUENRG1_GPIO_IRQ_DEVICE_H_ */
